### ISSUE TITLE
大佬，能分享一下数据吗

### ISSUE THREAD

**Issue by aesdhj** [shyoulala/CCF_BDCI_2020_DIDI_rank1_solution#3]
大佬，能分享一下数据吗

**Comment by shyoulala** [comment]
sorry,貌似比赛官方不经允许不能分享数据。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shyoulala/CCF_BDCI_2020_DIDI_rank1_solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 晚上11:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[shyoulala/CCF_BDCI_2020_DIDI_rank1_solution] 大佬，能分享一下数据吗 (Issue #3)





 
大佬，能分享一下数据吗

**Comment by shyoulala** [comment]
貌似官方不让开源数据， 你可以看看这里能不能申请：https://outreach.didichuxing.com/app-vue/dataList


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shyoulala/CCF_BDCI_2020_DIDI_rank1_solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shyoulala/CCF_BDCI_2020_DIDI_rank1_solution] 大佬，能分享一下数据吗 (Issue #3)





 
Closed #3 as completed.
