### ISSUE TITLE
nn_train_and_test中的scaled_features里面包含过去时段的label值，为什么能标准化

### ISSUE THREAD

**Issue by aesdhj** [shyoulala/CCF_BDCI_2020_DIDI_rank1_solution#4]
nn_train_and_test中的scaled_features里面包含过去时段的label值，为什么能标准化，不是很理解，应该是分类标签把

**Comment by shyoulala** [comment]
可以理解为label也可以强弱，当做浮点数&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shyoulala/CCF_BDCI_2020_DIDI_rank1_solution"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午5:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[shyoulala/CCF_BDCI_2020_DIDI_rank1_solution] nn_train_and_test中的scaled_features里面包含过去时段的label值，为什么能标准化 (Issue #4)





 
nn_train_and_test中的scaled_features里面包含过去时段的label值，为什么能标准化，不是很理解，应该是分类标签把
